export var pilotos = [
    {
        id: 1,
        nombre: "George",
        apellido: "Russell",
        nacionalidad: "Británico",
        escuderia: "MERCEDES",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/george-russell.jpg",
    },

    {
        id: 2,
        nombre: "Lewis",
        apellido: "Hamilton",
        nacionalidad: "Británico",
        escuderia: "MERCEDES",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/lewis-hamilton.jpg",
    },
    {
        id: 3,
        nombre: "Pierre",
        apellido: "Gasly",
        nacionalidad: "Francés",
        escuderia: "ALPINE",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/pierre-gasly.jpg",
    },
    {
        id: 4,
        nombre: "Esteban",
        apellido: "Ocon",
        nacionalidad: "Francés",
        escuderia: "ALPINE",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/esteban-ocon.jpg",
    },
    {
        id: 5,
        nombre: "Nico",
        apellido: "Hulkenberg",
        nacionalidad: "Alemán",
        escuderia: "HAAS",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/nico-hulkenberg.jpg",
    },
    {
        id: 6,
        nombre: "Kevin",
        apellido: "Magnussen",
        nacionalidad: "Danés",
        escuderia: "HAAS",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/kevin-magnussen.jpg",
    },
    {
        id: 7,
        nombre: "Lando",
        apellido: "Norris",
        nacionalidad: "Británico",
        escuderia: "MCLAREN",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/lando-norris.jpg",
    },
    {
        id: 8,
        nombre: "Oscar",
        apellido: "Piastri",
        nacionalidad: "Australiano",
        escuderia: "MCLAREN",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/oscar-piastri.jpg",
    },
    {
        id: 9,
        nombre: "Max",
        apellido: "Verstappen",
        nacionalidad: "Neerlandés",
        escuderia: "RED BULL",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/max-verstappen.jpg",
    },
    {
        id: 10,
        nombre: "Sergio",
        apellido: "Pérez",
        nacionalidad: "Mexicano",
        escuderia: "RED BULL",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/sergio-perez.jpg",
    },
    {
        id: 11,
        nombre: "Fernando",
        apellido: "Alonso",
        nacionalidad: "Español",
        escuderia: "ASTON MARTIN",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/fernando-alonso.jpg",
    },
    {
        id: 12,
        nombre: "Lance",
        apellido: "Stroll",
        nacionalidad: "Canadiense",
        escuderia: "ASTON MARTIN",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/lance-stroll.jpg",
    },
    {
        id: 13,
        nombre: "Yuki",
        apellido: "Tsunoda",
        nacionalidad: "Japonés",
        escuderia: "ALPHATAURI",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/yuki-tsunoda.jpg",
    },
    {
        id: 14,
        nombre: "Nyck",
        apellido: "de Vries",
        nacionalidad: "Neerlandés",
        escuderia: "ALPHATAURI",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/nyck-de-vries.jpg",
    },
    {
        id: 15,
        nombre: "Charles",
        apellido: "Leclerc",
        nacionalidad: "Monegasco",
        escuderia: "FERRARI",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/charles-leclerc.jpg",
    },
    {
        id: 16,
        nombre: "Carlos",
        apellido: "Sainz",
        nacionalidad: "Español",
        escuderia: "FERRARI",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/carlos-sainz.jpg",
    },
    {
        id: 17,
        nombre: "Valtteri",
        apellido: "Bottas",
        nacionalidad: "Finlandés",
        escuderia: "ALFA ROMEO",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/valtteri-bottas.jpg",
    },
    {
        id: 18,
        nombre: "Guanyu",
        apellido: "Zhou",
        nacionalidad: "Chino",
        escuderia: "ALFA ROMEO",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/guanyu-zhou.jpg",
    },
    {
        id: 19,
        nombre: "Alexander",
        apellido: "Albon",
        nacionalidad: "Tailandés",
        escuderia: "WILLIAMS",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/alexander-albon.jpg",
    },
    {
        id: 20,
        nombre: "Logan",
        apellido: "Sargeant",
        nacionalidad: "Estadounidense",
        escuderia: "WILLIAMS",
        puntuacion: 0,
        propiedadJugador: "",
        rol: "",
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/pilotos/logan-sargeant.jpg",
    },
];

export var puntuaciones = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1];

export var grandesPremios = [
    {
        id: 1,
        nombre: "Gran Premio de Bahréin",
        ubicacion: "Sakhir",
        descripcion:
            "La longitud del circuito es de 5,412 kilómetros. Durante la carrera se dan 57 vueltas al circuito cubriendo una distancia final de 308,484 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/bahrein.png",
    },
    {
        id: 2,
        nombre: "Gran Premio de Arabia Saudí",
        ubicacion: "Jeddah",
        descripcion:
            "La longitud del circuito es de 6,174 kilómetros. Durante la carrera se darán 50 vueltas al circuito cubriendo una distancia final de 308,700 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/arabia-saudi.png",
    },
    {
        id: 3,
        nombre: "Gran Premio de Australia",
        ubicacion: "Melbourne",
        descripcion:
            "La longitud del circuito es de 5,303 kilómetros. Durante la carrera se dan 58 vueltas al circuito cubriendo una distancia final de 307,574 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/australia.png",
    },
    {
        id: 4,
        nombre: "Gran Premio de Azerbaiyán",
        ubicacion: "Bakú",
        descripcion:
            ". La longitud del circuito es de 6,003 kilómetros. Durante la carrera se dan 51 vueltas al circuito cubriendo una distancia final de 306,153 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/baku.png",
    },
    {
        id: 5,
        nombre: "Gran Premio de Miami",
        ubicacion: "Miami",
        descripcion:
            "La longitud del circuito es de 5,412 kilómetros. Durante la carrera se dan 57 vueltas al circuito cubriendo una distancia final de 308,484 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/miami.png",
    },
    {
        id: 6,
        nombre: "Gran Premio de Emilia-Romaña",
        ubicacion: "Imola",
        descripcion:
            "La longitud del circuito es de 4,909 kilómetros. Durante la carrera se dan 63 vueltas al circuito cubriendo una distancia final de 309,267 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/emilia-romana.png",
    },
    {
        id: 7,
        nombre: "Gran Premio de Mónaco",
        ubicacion: "Montecarlo",
        descripcion:
            "La longitud del circuito es de 3,337 kilómetros. Durante la carrera se dan 78 vueltas al circuito cubriendo una distancia final de 260,286 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/monaco.png",
    },
    {
        id: 8,
        nombre: "Gran Premio de España",
        ubicacion: "Montmeló (Barcelona)",
        descripcion:
            "La longitud del circuito es de 4,675 kilómetros. Durante la carrera se dan 66 vueltas al circuito cubriendo una distancia final de 308,550 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/barcelona.png",
    },
    {
        id: 9,
        nombre: "Gran Premio de Canadá",
        ubicacion: "Montreal",
        descripcion:
            "La longitud del circuito es de 4,361 kilómetros. Durante la carrera se dan 70 vueltas al circuito cubriendo una distancia final de 305,270 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/canada.png",
    },
    {
        id: 10,
        nombre: "Gran Premio de Austria",
        ubicacion: "Spielberg (Austria)",
        descripcion:
            "La longitud del circuito es de 4,318 kilómetros. Durante la carrera se dan 71 vueltas al circuito cubriendo una distancia final de 306,578 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/austria.png",
    },
    {
        id: 11,
        nringausombre: "Gran Premio de Gran Bretaña",
        ubicacion: "Silverstone (Reino Unido)",
        descripcion:
            "La longitud del circuito es de 5,891 kilómetros. Durante la carrera se dan 52 vueltas al circuito cubriendo una distancia final de 306,332 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/silverstone.png",
    },
    {
        id: 12,
        nombre: "Gran Premio de Hungría",
        ubicacion: "Hungaroring (Budapest)",
        descripcion:
            "La longitud del circuito es de 4,381 kilómetros. Durante la carrera se dan 70 vueltas al circuito cubriendo una distancia final de 306,670 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/hungaroring.png",
    },
    {
        id: 13,
        nombre: "Gran Premio de Bélgica",
        ubicacion: "Spa",
        descripcion:
            "La longitud del circuito es de 7,004 kilómetros. Durante la carrera se dan 44 vueltas al circuito cubriendo una distancia final de 308,176 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/spa.png",
    },
    {
        id: 14,
        nombre: "Gran Premio de los Países Bajos",
        ubicacion: "Zandvoort",
        descripcion:
            "La longitud del circuito es de 4,259 kilómetros. Durante la carrera se dan 72 vueltas al circuito cubriendo una distancia final de 306,648 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/paises-bajos.png",
    },
    {
        id: 15,
        nombre: "Gran Premio de Italia",
        ubicacion: "Monza",
        descripcion:
            "La longitud del circuito es de 5,793 kilómetros. Durante la carrera se dan 53 vueltas al circuito cubriendo una distancia final de 307,029 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/monza.png",
    },
    {
        id: 16,
        nombre: "Gran Premio de Singapur",
        ubicacion: "Singapur",
        descripcion:
            "La longitud del circuito es de 5,063 kilómetros. Durante la carrera se dan 61 vueltas al circuito cubriendo una distancia final de 308,843 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/singapur.png",
    },
    {
        id: 17,
        nombre: "Gran Premio de Japón",
        ubicacion: "Suzuka",
        descripcion:
            "La longitud del circuito es de 5,807 kilómetros. Durante la carrera se dan 53 vueltas al circuito cubriendo una distancia final de 307,771 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/suzuka.png",
    },
    {
        id: 18,
        nombre: "Gran Premio de Qatar",
        ubicacion: "Lusail",
        descripcion:
            "La longitud del circuito es de 5,38 kilómetros. Durante la carrera se dan 57 vueltas al circuito cubriendo una distancia final de 306,660 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/bahrein.png",
    },
    {
        id: 19,
        nombre: "Gran Premio de Estados Unidos",
        ubicacion: "Austin (Texas)",
        descripcion:
            "La longitud del circuito es de 5,513 kilómetros. Durante la carrera se dan 56 vueltas al circuito cubriendo una distancia final de 308,728 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/austin.png",
    },
    {
        id: 20,
        nombre: "Gran Premio de México",
        ubicacion: "Ciudad de México",
        descripcion:
            "La longitud del circuito es de 4,304 kilómetros. Durante la carrera se dan 71 vueltas al circuito cubriendo una distancia final de 305,584 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/mexico.png",
    },
    {
        id: 21,
        nombre: "Gran Premio de Brasil",
        ubicacion: "São Paulo",
        descripcion:
            "La longitud del circuito es de 4,309 kilómetros. Durante la carrera se dan 71 vueltas al circuito cubriendo una distancia final de 305,939 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/brasil.png",
    },
    {
        id: 22,
        nombre: "Gran Premio de Las Vegas",
        ubicacion: "Las Vegas",
        descripcion:
            "La longitud del circuito es de 6,12 kilómetros. Durante la carrera se dan 50 vueltas al circuito cubriendo una distancia final de 306,000 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/las-vegas.png",
    },
    {
        id: 23,
        nombre: "Gran Premio de Abu Dhabi",
        ubicacion: "Abu Dabi (Emiratos Árabes)",
        descripcion:
            "La longitud del circuito es de 5,281 kilómetros. Durante la carrera se dan 58 vueltas al circuito cubriendo una distancia final de 306,298 kilómetros.",
        posiciones: [
            { idPiloto: 0, posicion: 0 },
            { idPiloto: 0, posicion: 0 },
        ],
        disputado: false,
        srcFoto: "https://oscardespliegue.000webhostapp.com/fotosf1/assets/img/circuitos/abu-dhabi.png",
    },
];
